### PR TITLE
Css three column layout- David Gonzalez

### PR DESCRIPTION
**Pull request by David-Gonzalez11**
Screen Shot 2022-05-13 at 8 44 40 AM

### CODE REVIEW

**Review by Zhiwutian — CHANGES_REQUESTED** [review]
its looking good David, the only thing I would update to get a look closer to the example is to make sure the image is centered within the column. 

A good way to approach this is to set `display flex` and `flex direction column` on the column class so then you can use `justify content center` in order to center all of the elements in the column, reach out if you have questions

**Comment by David-Gonzalez11** [comment]
image

**Comment by David-Gonzalez11** [comment]
image

**Review by Zhiwutian — APPROVED** [review]
👍🏼

**Pull request merged**
